### ISSUE TITLE
No signature file?

### ISSUE THREAD

**Issue by LordArcanon** [satisfactorymodding/SatisfactoryModLoader#106]
Version: 131382, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: -, NetMode: -, IsUsingMods: No

Assertion failed: [File:D:\ws\SB-200518130817-657\UE4\Engine\Source\Runtime\PakFile\Private\SignedArchiveReader.cpp] [Line: 44] Couldn't find pak signature file '../../../FactoryGame/Mods/SML/Content/Paks/WindowsNoEditor/SMLFactoryGame-WindowsNoEditor.sig'

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::AssertFailed() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:449]
FactoryGame_Win64_Shipping!FChunkCacheWorker::FChunkCacheWorker() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\signedarchivereader.cpp:44]
FactoryGame_Win64_Shipping!FPakFile::SetupSignedPakReader() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\iplatformfilepak.cpp:4202]
FactoryGame_Win64_Shipping!FPakFile::GetSharedReader() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\iplatformfilepak.cpp:4948]
FactoryGame_Win64_Shipping!FPakFile::FPakFile() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\iplatformfilepak.cpp:4142]
FactoryGame_Win64_Shipping!FPakPlatformFile::Mount() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\iplatformfilepak.cpp:5409]
FactoryGame_Win64_Shipping!FPakPlatformFile::HandleMountPakDelegate() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\pakfile\private\iplatformfilepak.cpp:5645]
FactoryGame_Win64_Shipping!FPluginManager::ConfigureEnabledPlugins() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\projects\private\pluginmanager.cpp:638]
FactoryGame_Win64_Shipping!FPluginManager::LoadModulesForEnabledPlugins() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\projects\private\pluginmanager.cpp:973]
FactoryGame_Win64_Shipping!FEngineLoop::AppInit() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4542]
FactoryGame_Win64_Shipping!FEngineLoop::PreInit() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:1729]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launch.cpp:129]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by budak7273** [comment]
Closing this issue since it has been resolved by updates to the base game and SML.
