### ISSUE TITLE
Customizer hides FICSIT when using ANY mod

### ISSUE THREAD

**Issue by bluetidepro** [satisfactorymodding/SatisfactoryModLoader#113]
When I enable any mod in SMM/SML, I lose the FICSIT options in the customizer.

**This is the bug:**

![Screenshot (140)](https://user-images.githubusercontent.com/410701/143317067-a0d709bf-4c26-4f7c-b16a-982a8a3a2221.png)

**It should look like this:** 

![Screenshot (142)](https://user-images.githubusercontent.com/410701/143317073-fc7dae6c-13bb-49ed-8fb2-3cec8f819332.png)

Just for reference, here are the mods I tried. Any of these turned on, causes the bug. If they are all turned off, then it's fine.

![Screenshot (141)](https://user-images.githubusercontent.com/410701/143317072-25fcec67-c625-4a0d-9b89-543c36f4c21b.png)

I am assuming it's a SML/SMM problem, if it happens with any mod, but I could be wrong. I figured I'd post it here, in case.

**Comment by archangelpaladin** [comment]
I can repo as well. Any mod enabled and they are gone.  Something that might help.  In my steps to debug I reset all my technology to zero(using the online editor) and re did all the milestones, awesome sink, research, and they came back, however after saving, quitting, and reloading the FICSIT options were gone again, something on startup is doing this.

**Comment by mircearoata** [comment]
The recipes were not registered in SML's content registry because they were not referenced directly by a schematic, so it removed them. Fixed in v3.2.1
