### ISSUE TITLE
Meshes from mod crashes game at start up. 

### ISSUE THREAD

**Issue by iceman11a** [satisfactorymodding/SatisfactoryModLoader#121]
I don't know if I'm the only one having this issue. I couldn't get any help from anyone to help me find out what was causing the crashes. I learn that the meshes in some way are causing the game to crash when I try and run my mod. 

Here's the error I get. 

 Assertion failed: Texture->VolumeData.CompressedDistanceFieldVolume.Num() == Size.X * Size.Y * Size.Z * FormatSize [File:D:/ws/SB-211116092526-440/UE4/Engine/Source/Runtime/Engine/Private/DistanceFieldAtlas.cpp] [Line: 687]

I got the idea that my texture was causing it. So I changes to Material and made a new one. Still the same issue. Crashes the game. 
So I change the mesh to a cube and that seems to have worked. The game loaded in just fine. I add the material to that cube and It still worked. The game loaded. So I don't understand what part of the mesh is doing this. I loaded the mesh into Blender and exported to and deleted the 1 I have in the project and put the mesh I edited into the project. and again the same error. Game crashes at startup.

**Comment by Feyko** [comment]
Issues on this repo isn't for help with making mods. I'll be asking an org admin to remove/close this issue

**Comment by Ryder17z** [comment]
Your better off trying to contact the person who made that mod on discord and discuss the issue there.

See https://ficsit.app/guide/AYVEPJd3Fi1oxa  to find the link to the modding chat.
