### ISSUE TITLE
Alpakit: Fails to package SOME mods, IO error

### ISSUE THREAD

**Issue by Basement-Science** [satisfactorymodding/SatisfactoryModLoader#123]
I'm having issues packaging **_some_** Mods using Alpakit. I've made my own mods (the example projects, and [my speedometer mod](https://github.com/Basement-Science/SatisfactoryMod_Speedo)), those package and work just fine. However I'm getting an Error with both the AssetDumper mod and also with [AreaActions](https://github.com/mircearoata/SatisfactoryAreaActions) which I tried to build (master branch/ v1.6.6).

The stacktrace is below, main line translates to `"a part of the path <...> could not be found"`. SML is up to date and tracked using git etc. Also tried setting up the Modding project again, no change.

```
UATHelper: Package Mod Task (Windows): ERROR: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "E:\Users\<...>\SatisfactoryModLoader\Plugins\SatisfactoryAreaActions\Saved\StagedBuilds\WindowsNoEditor\FactoryGame\Mods\AreaActions" konnte nicht gefunden werden.
UATHelper: Package Mod Task (Windows):           bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
UATHelper: Package Mod Task (Windows):           bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
UATHelper: Package Mod Task (Windows):           bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
UATHelper: Package Mod Task (Windows):           bei System.IO.DirectoryInfo.EnumerateFileSystemInfos(String searchPattern, SearchOption searchOption)
UATHelper: Package Mod Task (Windows):           bei System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
UATHelper: Package Mod Task (Windows):           bei System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName)
UATHelper: Package Mod Task (Windows):           bei Alpakit.Automation.PackagePlugin.ArchivePluginProject(ProjectParams projectParams, IEnumerable`1 deploymentContexts)
UATHelper: Package Mod Task (Windows):           bei Alpakit.Automation.PackagePlugin.ExecuteBuild()
UATHelper: Package Mod Task (Windows):           bei AutomationTool.BuildCommand.Execute()
UATHelper: Package Mod Task (Windows):           bei AutomationTool.Automation.Execute(List`1 CommandsToExecute, Dictionary`2 Commands)
UATHelper: Package Mod Task (Windows):           bei AutomationTool.Automation.Process(String[] Arguments, StartupTraceListener StartupListener)
UATHelper: Package Mod Task (Windows):           bei AutomationTool.Program.MainProc(String[] Arguments, StartupTraceListener StartupListener)
UATHelper: Package Mod Task (Windows):           bei AutomationTool.Program.<>c__DisplayClass1_0.<Main>b__2()
UATHelper: Package Mod Task (Windows):           bei AutomationTool.InternalUtils.RunSingleInstance(Func`1 Main)
UATHelper: Package Mod Task (Windows):           bei AutomationTool.Program.Main(String[] Arguments)
```

**Comment by mircearoata** [comment]
A couple limitations with Alpakit currently:

* the plugin folder name has to be the same as the plugin name (i.e. `AreaActions` rather than `SatisfactoryAreaActions`)
* and the plugin folder must be directly inside the `Plugins` directory (i.e. `Plugins\AssetDumper` rather than `Plugins\UEAssetToolkit\AssetDumper`)

Those two are the same issue, Alpakit looks inside the `...\StagedBuilds\...\Mods\PluginName`, but the files are actually placed by UE in `...\StagedBuilds\...\Mods\Relative\Path\To\Plugins\Dir`

**Comment by Basement-Science** [comment]
>     * the plugin folder name has to be the same as the plugin name (i.e. `AreaActions` rather than `SatisfactoryAreaActions`)
>     * and the plugin folder must be directly inside the `Plugins` directory (i.e. `Plugins\AssetDumper` rather than `Plugins\UEAssetToolkit\AssetDumper`)

Thanks a lot, yep those were the issues. Would be great if there was at least an appropriate warning or error message. Didnt find anything about such issues when I started using it either.
