### ISSUE TITLE
Update Docs from SML version 2.2.1

### ISSUE THREAD

**Issue by PrivacyOsint2** [satisfactorymodding/SatisfactoryModLoader#125]
Please Update the docs on this page. I'm trying to figure out what dir the https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/latest  needs to go. Need some help.

Link of Docs:
https://docs.ficsit.app/satisfactory-modding/latest/ManualInstallDirections.html#_installing_mods_on_linux_steam_as_a_player_sml_version_2_2_1

Will the lastest 3.3.0 work in linux? If not what is the last version that was working. Thanks

**Comment by EV0LV3** [comment]
"Please Update the docs on this page. I'm trying to figure out what dir the https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/latest needs to go. Need some help."

Under windows: X:\Steam\steamapps\common\Satisfactory\FactoryGame\Mods\SML
But if you try this on a windows dedicaded server, it is not working yet. See: https://discord.com/channels/555424930502541343/555785224873574410/912479173224824832

3.3.0 will not work on linux see: https://docs.ficsit.app/satisfactory-modding/latest/ManualInstallDirections.html#_installing_mods_on_linux_steam_as_a_player_sml_version_2_2_1

And then see the warning message:
`This was written for SML 2.2.1 and is out of date.
Please contact us with revised Linux directions to put here, or send a PR via Edit This Page.`

`This was written for SML 2.2.1 and is out of date. Please contact us with revised Linux directions to put here, or send a PR via Edit This Page.`

"If not what is the last version that was working. Thanks"
I think 2.2.1 was the last version that was working on linux. But im not sure.

**Comment by mircearoata** [comment]
SML 3.3.0 does work on linux, and those steps mentioned there are no longer needed, as the way SML is loaded has changed in SML 3. Everything works out of the box on linux using the [Satisfactory Mod Manager](https://github.com/satisfactorymodding/SatisfactoryModManager)

**Comment by budak7273** [comment]
As noted at the top of the linked page, "THIS IS UNSUPPORTED → NO SUPPORT SHOULD BE EXPECTED FOR ANYONE ATTEMPTING THIS." No support will be offered for those directions.

As Mircea mentioned, SML 3.3.0 works out of the box on Linux via Satisfactory Mod Manager, and as EV0LV3 said, dedicated server support is still in progress and not ready yet.

I'll update the docs page to remove the outdated instructions.
