### ISSUE TITLE
Error While loading profile

### ISSUE THREAD

**Issue by serifkazan** [satisfactorymodding/SatisfactoryModLoader#137]
I have the last version of smm but when i try to update mods i got the following error.

![image](https://user-images.githubusercontent.com/6292861/189480165-490b0ad1-c9b2-4a58-9f0a-d11763d7b1f8.png)

**Comment by budak7273** [comment]
Please generate debug info and send it on the modding discord as described in the popup, or open an issue on the [Mod Manager repo](https://github.com/satisfactorymodding/SatisfactoryModManager). This issue does not relate to SML.
