### ISSUE TITLE
M.A.M Difficulties - Involvement of FICSMAS when not needed!

### ISSUE THREAD

**Issue by JackiTacki** [satisfactorymodding/SatisfactoryModLoader#149]
It's a simple thing;

CURRENT ISSUE; When any mod is loaded, Most likely the culprit itself being SMM's Loader, The FICSMAS tree in the M.A.M. will open despite it not being December 1st, Nor any provoking to the unlocking of said tree. This of course to most is something most might not care about, But to people like me seeing a tree just. . .Unlocked and with nothing to do involving it, It's a bit annoying! 

Of course this is a very small, Inconvenient thing, And should take no priority over important things. I'm just hoping it's a thing that can get resolved, To where FICSMAS only appears during the days it's released. This is a very recent thing, And others have noticed it as well.

Thanks for reading lovelies, Have a vanderful day - And may the factories grow!

**Comment by budak7273** [comment]
This was fixed in [v3.4.1](https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/tag/v3.4.1), thanks for reporting it here.
