### ISSUE TITLE
Expose "Enable Blueprint Usage"?

### ISSUE THREAD

**Issue by johnvilsack** [satisfactorymodding/SatisfactoryModLoader#158]
When you unlock Tier 4's Blueprint Designer, the game also gets you the ability to use blueprints. However, it seems that Enabling Blueprint Usage is decoupled for the actual item itself.

If possible, a boolean BlueprintUseEnabled command would integrate nicely into SMLs existing structure. I can see this being useful for players that have gone through multiple playthroughs, as well as even possibly giving admins more granular control if the feature proves to be useful for cheating/griefing.

**Comment by budak7273** [comment]
I'm not sure if I understand what you're asking, but it sounds like you're looking for a mod that grants access to the blueprint designer earlier than Tier 4. This would be the responsibility of a mod to set up and trigger, not the mod loader.

**Comment by budak7273** [comment]
This mod implements the functionality you described: https://ficsit.app/mod/EarlyAndFreeBlueprintDesigner
