### ISSUE TITLE
.exe file not in binaries folder

### ISSUE THREAD

**Issue by Blockbuilder02** [satisfactorymodding/SatisfactoryModLoader#162]
The FactoryGame-Win64-Shipping.exe file does not exist in the binaries folder there is only a .modules and a .dll file which require a specific application to open. What do i do?
![image_2023-01-22_194129858](https://user-images.githubusercontent.com/123324691/213933819-f12797e6-877d-4de1-9cdb-139068a0adfe.png)

**Comment by Panakotta00** [comment]
It exists in the Engine Binaries Folder

**Comment by budak7273** [comment]
`\SatisfactoryEarlyAccess\Engine\Binaries\Win64\FactoryGame-Win64-Shipping.exe`
