### ISSUE TITLE
Commit the Visual Studio project file generation fixes

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModLoader#171]
https://github.com/SatisfactoryModdingUE/UnrealEngine/

https://discord.com/channels/555424930502541343/562722670974599227/1107196205936676954

**Comment by mircearoata** [comment]
https://github.com/SatisfactoryModdingUE/UnrealEngine/commit/a64ac8f05d1a14ca5694aa0c1fedbede937d0fc6
