### ISSUE TITLE
Dedicated server support

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModLoader#179]

**Comment by budak7273** [comment]
Implemented on dedicated servers branch

**Comment by TheLargeCactus** [comment]
What are the odds this is working for U8?

**Comment by budak7273** [comment]
All mods must be specifically recompiled under new settings, so even if it is working for U8, you would need to build every mod you want to play with from source yourself.

**Comment by rcannood** [comment]
I'm a little confused. If that's all there is to it, why not merge the
dedicated server branch into master? There are so many people who'd like to
play modded multiplayer games but can't.

**Comment by budak7273** [comment]
@rcannood Merging the dedicated server branch into master does not mean people would be able to play on dedicated servers because there is still more work to be done in the distribution and installation of dedicated server mods. Also, the functionality has not been tested again since U8 changes have been brought in, we've been working on the stuff that just came out in 3.6.1.

It's important to note that **mods already work in host and play multiplayer**, as long as the individual mod supports it. People who want to play multiplayer with mods already can via host and play.

Check out these boards to see more info on what is left to do:
- https://github.com/orgs/satisfactorymodding/projects/10
- https://github.com/orgs/satisfactorymodding/projects/7
