### ISSUE TITLE
SML crashed 

### ISSUE THREAD

**Issue by xStreeter** [satisfactorymodding/SatisfactoryModLoader#19]
I just installed the newest version of SML and some mods correctly (step by step) but for some reason while loading SML crashes.

![Unbenannt1](https://user-images.githubusercontent.com/57009100/67581973-311a6f00-f749-11e9-907e-1939c61c0ee5.PNG)

**Comment by mircearoata** [comment]
As the error says, you need to download the SID (SatisfactoryItemDictionary) mod too

**Comment by SuperCoder7979** [comment]
Not an SML error.

**Comment by xStreeter** [comment]
I just noticed that i overlooked to install
![Unbenannt2](https://user-images.githubusercontent.com/57009100/67583158-5c9e5900-f74b-11e9-984e-864ea0d981df.PNG)
 SID, but now I'm having another issue

**Comment by mircearoata** [comment]
Verify the game files from the launcher
