### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by ilikesatisfactory** [satisfactorymodding/SatisfactoryModLoader#20]
Hi!

When I want to start satisfactory it says: Your Satisfactory mod loader is too old to update press OK, I pressed OK, now It says SID_p is missing, make sure you installed the mod loader properly.

Please help!

Thanks,
Mark

**Comment by SuperCoder7979** [comment]
For the update issue: update your satisfactory. If it's already updated, reinstall it.  For the SID issue, install SatisfactoryItemDictionary from https://ficsit.app.

**Comment by ilikesatisfactory** [comment]
Thank You for your help!
