### ISSUE TITLE
ExampleLevel gas pillars do not have the gas cloud visuals

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModLoader#213]

**Comment by Th3Fanbus** [comment]
I have fixed this in https://discord.com/channels/555424930502541343/1302190715308343407 but I haven't made a PR yet. It'll probably have a bunch of stuff as I've been working on several other things for ExampleLevel.

**Comment by Th3Fanbus** [comment]
Video of it working: https://discord.com/channels/555424930502541343/623891487683510323/1302242451200675840

**Comment by Th3Fanbus** [comment]
Fix is part of https://github.com/satisfactorymodding/SatisfactoryModLoader/pull/311

**Comment by budak7273** [comment]
Fixed in #311
