### ISSUE TITLE
SML Loader issues 

### ISSUE THREAD

**Issue by p1H3u7u7n5** [satisfactorymodding/SatisfactoryModLoader#24]
SML Version check failed for Satisfactory

Running Satisfactory Ver. 106504
SML Latest Ver. 1.0.2 

Still cannot load

[SatisfactoryModLoader.log](https://github.com/satisfactorymodding/SatisfactoryModLoader/files/3827853/SatisfactoryModLoader.log)

Mods also do not show in game

**Comment by SuperCoder7979** [comment]
Try updating Satisfactory or try reinstalling it, hopefully either of those fixes your issue

**Comment by p1H3u7u7n5** [comment]
BTW has anyone been having problems using the tab key to select Tool Options Mine keeps on crashing every time i try to click the tab key

**Comment by p1H3u7u7n5** [comment]
SML states current version of Satisfactory is too old for SML

**Comment by mspi51** [comment]
Having same issue.  tried to reload, same issue.  Is there suppose to be a SID_p.pak in the item dictionary download?

**Comment by Ryder17z** [comment]
> Having same issue. tried to reload, same issue. Is there suppose to be a SID_p.pak in the item dictionary download?

If you need it see the wiki: https://github.com/satisfactorymodding/SatisfactoryModLoader/wiki/FAQ

**Comment by SuperCoder7979** [comment]
> BTW has anyone been having problems using the tab key to select Tool Options Mine keeps on crashing every time i try to click the tab key
I'm sorry, what do you mean by that?
> SML states current version of Satisfactory is too old for SML
Did you try the fixes I suggested?
> Having same issue. tried to reload, same issue. Is there suppose to be a SID_p.pak in the item dictionary download?
Try the fixes I suggested too. If that doesn't work, reply again and we can try to diagnose the issue further.

**Comment by p1H3u7u7n5** [comment]
Have seen no replies, have also tried reinstalling the game and SML Still is incompatible. SML cannot verify Satisfactory Version of Game Running

**Comment by Ryder17z** [comment]
> Have seen no replies, have also tried reinstalling the game and SML Still is incompatible. SML cannot verify Satisfactory Version of Game Running

Experimental or normal version?

**Comment by gregcor72** [comment]
Downloaded Experimental this morning and dropped the .dll in and the game refuses to start. The console window pops up real quick then the Epic Games Loader reloads. The Satisfactory Game logo never even comes up. Experimental runs fine without SML. EA runs fine with SML, using the same (latest) .dll. I tried deleting and reloading Experimental, verifying the files and even started a fresh game with no mods first to make sure it worked.

**Comment by Vilsol** [comment]
@gregcor72 We are aware that SML currently doesn't support experimental. That is due to the games engine upgrade. We are hoping to release a compatible version in the next few weeks.

**Comment by gregcor72** [comment]
@Vilsol Ok, thanks.

**Comment by SuperCoder7979** [comment]
Seeing as the issues here have been resolved, I'm gonna close this issue.
