### ISSUE TITLE
Can't start game after download

### ISSUE THREAD

**Issue by patfr** [satisfactorymodding/SatisfactoryModLoader#25]
#24  downloaded a new version of the mod loader and put it in and now every time i try to start the game the other window came up and closed shortly after and the game won't open. it is the 1.0.2 sml.

**Comment by Vilsol** [comment]
Are you on Early Access or Experimental game branch?

**Comment by JustinGalbraith** [comment]
I'm having the same issue with the Experimental Build which seems to have started very recently. If I remove xinput1_3.dll 1.0.2 the game will launch. I've also tried launching with 1.0.1 but that doesn't resolve the issue. I've even tried removing all mod files completely while leaving xinput1_3.dll, but I was still unable to launch. 

The game will launch in the Early Access build with all the same mod and xinput1_3.dll files.

**Comment by SuperCoder7979** [comment]
SML doesn't work with experimental yet so you should stick with early access for now.

**Comment by JustinGalbraith** [comment]
Good to know. Thanks!

**Comment by patfr** [comment]
Oh thanks i didn't want to check the early access in case i wouldn't  be able to start it either also i installed it on my hard drive in stead of my ssd so i uninstalled it and it will take a long time to download again so i didn't want to risk it but thanks for helping.

**Comment by floven1** [comment]
as an additional note, verifying fixes this issue if you also delete the xinput1_3.dll but just to be clear: THIS DOES NOT ALLOW YOU TO INSTALL MODS, IT ONLY ALLOWS YOU TO BOOT THE VANILLA GAME AGAIN AFTER INSTALLING THE WRONG MODLOADER!

**Comment by justToSaveMyProjects** [comment]
If I have any mods installed in the Satisfactory Mod Manager, I cannot start the game netiher from the Mod Manager or Steam.
If I uninstall all the mods, both can launch the game.
Could you help me out, what am I missing / should look for?


I know this is less than nothing to start debugging so I am just gonna write some info that might help :D 
OS: Windows 10 Pro
Version: 2004
Build: 19041.630
CPU: Intel(R) Core(TM) i7-6700
GPU: NVIDIA GeForce GRX 960

**Comment by mircearoata** [comment]
This isn't the same issue as the original one, that was because the game updated so no mods worked for a while.

Yours is the bootstrapper crashing while loading SML to the game. It works if you start the game directly from the exe in the game install dir
