### ISSUE TITLE
Alpakit doesn't clean up old staged builds on disable plugin

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModLoader#255]
https://discord.com/channels/555424930502541343/562722670974599227/1199294990233387109

This means if you do the `.uplugin.disabled` trick mentioned in the docs you must manually clean up the old staged copy of the mod before you're able to build the project again

**Comment by mircearoata** [comment]
CopyBuildToStagingDirectory (one of the steps of BuildCookRun) cleans the directory before copying the build using [this function](https://github.com/EpicGames/UnrealEngine/blob/5.2.1-release/Engine/Source/Programs/AutomationTool/Scripts/CopyBuildToStagingDirectory.Automation.cs#L4159), so we can use the same one at the end of the script, however, we need to make sure it runs even if the task fails.

**Comment by budak7273** [comment]
Fixed in d9ec09d3c9c5bb88e78917c64e7ee1bb1c6ba087
