### ISSUE TITLE
Game crashes when second player joins more than one time during session

### ISSUE THREAD

**Issue by Ig3l** [satisfactorymodding/SatisfactoryModLoader#28]
Hey there,

my friend and I discovered a weird bug. 

The one that is not hosting the session experiences some lag during longer gameplay. When the second player returns to main menu and then rejoins the session the game crashes for both partys.

This is reproducible every time. 

Attached Files
[Log-Player-2.txt](https://github.com/satisfactorymodding/SatisfactoryModLoader/files/4283080/Log-Player-2.txt)
[Log-Player-Host.txt](https://github.com/satisfactorymodding/SatisfactoryModLoader/files/4283081/Log-Player-Host.txt)
![ErrorMessage-Player-2](https://user-images.githubusercontent.com/34126314/75810293-9e3eb080-5d8a-11ea-8e6e-e3de401ce170.png)
![ErrorMessage-Player-Host](https://user-images.githubusercontent.com/34126314/75810298-9ed74700-5d8a-11ea-9f7f-73790a50368d.png)

______________________________________

I also noticed in the console that there are many dead links to files:

LogOutputDevice: Error: Ensure condition failed: bChunkHashesMatch [File:**C:\Jenkins\workspace\I_BuildVersion-staging\UE4\Engine\Source\Runtime\PakFile\Private\SignedArchiveReader.cpp**] [Line: 294]

This is not my device, so it must be something which is hardcoded by the developer?
It's the fifth log entry after SML initializes.

**Comment by Panakotta00** [comment]
Sorry but currently SML does not support multiplayer.
So issues related to multiplayer are ignored right now.
The log path is correct, but not hardcoded, the reason is, this path is used by CSS to actually know where in their code the exception occured.
