### ISSUE TITLE
Phase widget container scrollbar + library method to unlock a new Tier/phase

### ISSUE THREAD

**Issue by HolographicWings** [satisfactorymodding/SatisfactoryModLoader#285]
Hello, trying to add new tiers in a mod, post the end game.
I noticed it easy by simply changing the int of the "M Tech Tier" field in a schematic to > 9

But there are two issues when doing that.

**First issue :**
The new tiers will never be unlocked, i tried the SchematicManager → GiveAccesstoSchematics method which doesn't helped, and tried the "BP Unlock Schematic" unlock type inside of another schematic, that doesn't helped neither
![Image](https://github.com/user-attachments/assets/c39ddf9a-12ee-4ac3-8688-9ba1372c8a07)

Could we have any way to unlock a new tier ? That would be awesome for adding new content.

**Second issue :**
An overflow in the HUB HUD when there are more than 12 tiers
![Image](https://github.com/user-attachments/assets/1e9a7afd-621c-4227-8a54-c5c066f3e642)

The tiers are inside of an HorizontalBox

Two ideas for fixing that would be
- Just moving the HorizontalBox into a ScrollBox
- Adding a left and a right arrow to either scroll, either change the view from tier 0-9 to 10-19, etc

**Thanks you very much in advance for answering this request.**

_P.S. 
If theses require a feature request on the Satisfactory's QA website, i will do it.
If they require a whole mod or a lot of work on SML, i'm ready to financially fund this effort._

**Comment by budak7273** [comment]
Re: phase unlocking. I haven't looked at how phases are handled in vanilla but it used to be an enum. I don't know if we would add something to SML for this, but someone obviously has to figure out how to do it first.

Re: phase scrollbar. We have implemented other scrollbars in the past, but and sometimes Coffee Stain has later added those scroll bars, obsoleting ours. I could see us adding a phase scroll bar

**Comment by HolographicWings** [comment]
Hello, i did some progress on my side and i will release a mod which add a scroller![Image](https://github.com/user-attachments/assets/95dd945c-91d5-4e95-afbb-784880f9b101)

The last thing i can't do is to manually unlock the new tiersA simple blueprint/C++ method to increase a specific or the next tier would be awesome.
Could we have this addition ?

Thanks you in advance for your support.
