### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by ahutt23** [satisfactorymodding/SatisfactoryModLoader#30]
so i downloaded the dll put it in the appropriate folder the CP showed up with the last line being version check passed but then nhothing no mods folder just the mod loader log saying 
[SML::Info]    Attached SatisfactoryModLoader v1.0.2 to Satisfactory
[SML::Info]    Finding config file...
[SML::Info]    Validating system files...
[SML::Info]    Sig file in place!
[SML::Warning] Skipping already disabled crash reporter
[SML::Info]    Version check passed!
aswell as the CFG 
{
    "Chat Commands": true,
    "Console": true,
    "Debug": false,
    "Disable Crash Reporter": true,
    "Enable Unsafe Mode": false,
    "Supress Errors": false
}

**Comment by ahutt23** [comment]
wait does the latest version work on experi

**Comment by Panakotta00** [comment]
Nope, SML does not work for Big Update 3 yet...
SML 2.0 will release soon though, but then you will need to wait for the modders to update their mods to the new mod loader.
