### ISSUE TITLE
Mod remains in game when removed from ficsit

### ISSUE THREAD

**Issue by isoindisystems** [satisfactorymodding/SatisfactoryModLoader#34]
Hi!
A friend and me wanted to play some new mods, but my friend got a "missing mod error". We searched around and saw, that in my mod directory the productionplus mod was still there.
Maybe it would be good if the SML would sync the actual "installed" mods with the mod directory.
Awesome work guys, keep going!

**Comment by Ryder17z** [comment]
mods don't work in multiplayer (yet) - you both need to have the same mods loaded

**Comment by mircearoata** [comment]
It would be pretty difficult for SML to sync the mods, but at least it shows what mods the client has to install to match the host.
The issue with mods/versions removed from ficsit.app should be fixed in the next version which I will release today
Some mods are compatible with multiplayer, but most aren't. The ones that add items and recipes should be good, but custom buildings might have issues if they aren't specifically made for multiplayer

**Comment by isoindisystems** [comment]
Ok sorry, you got me completely wrong.
e.g.
Mods at mod repository at time 0: Mod 1, Mod 2, Mod 3
Installed mods at time 0: Mod 1, Mod 2, Mod 3
Mods at mod repository at time 1: Mod 1, Mod 2
Installed mods at time 1: Mod 1, Mod 2, Mod 3

As you can see I have all three mods installed at Time 1, but Mod 3 got removed from the Mod repository. I sent my friend a screenshot of SML to show him what mods he should install. The Screenshot contained Mod 1, Mod 2.
He installed Mod 1 and Mod 2, and then he got the error "Missing mod error".
After some research time I found the issue, SML was not displaying Mod 3 (because Mod 3 got removed from the mod repository), but Mod 3 was still installed in my game!
That was my issue about. SML should display what is installed and what mods are available. So in summary mod 3 was a zombie.

Regarding multiplayer and mods.
Well, we have many mods installed and we have absolutely no problems, all is working fine!

**Comment by mircearoata** [comment]
Oh, then this issue was for SMLauncher, not SML. Anyway, it was fixed in SMLauncher v1.0.4

**Comment by Archengius** [comment]
Not related to SML itself, it's SMLLauncher issue.
