### ISSUE TITLE
SML 2.1.1 calling Init before spawning initmod

### ISSUE THREAD

**Issue by Potenzo** [satisfactorymodding/SatisfactoryModLoader#45]
Results in Area Actions mod partially loading (mod runs but no actions).

https://discord.com/channels/555424930502541343/555516979260293132/707848200299479041

I kind of assume you're aware of this, but while the AA mod author has said it's an issue with SML and not his mod, I haven't seen any ack from the SML team. 

Since there were no open tickets here, I figured the right thing to do rather than bug people was to open this ticket. Either it'll be accepted and left/open worked on (in which case we'll know it's accepted as an SML bug), or rejected and closed, in which case we know there's a difference of opinion between the mod author and the SML team. Since the mod author think's its with SML he isn't working on a fix either, so if this ticket gets rejected we'll know AA is out of action for the foreseeable future. But if this ticket is accepted as a bug, we can hope for an SML fix that'll get AA up and running Real Soon Now (tm).

**Comment by mircearoata** [comment]
Fixed in SML 2.1.2
