### ISSUE TITLE
Attempting to log a string with a TM symbol causes execution to get stuck on the log node

### ISSUE THREAD

**Issue by BlogmasterAvery** [satisfactorymodding/SatisfactoryModLoader#50]
I encountered this problem with Log Error, did not test the other SML logging functions. This is a problem, because the factory cart contains a '™' in its item name, and if one was ever trying to put item names into the log like I was, their blueprint would just stop working.

**Comment by Archengius** [comment]
Need stack trace captured with debugger

**Comment by budak7273** [comment]
In SML 3.4.0, this no longer seems to crash, at least from a blueprint LogVerbose node. The character shows up correctly in the console, too.
