### ISSUE TITLE
Unable to add mods to existing savegame

### ISSUE THREAD

**Issue by SimonFischer04** [satisfactorymodding/SatisfactoryModLoader#57]
I started my savegame with 38 mods. Now everytime I add a new mod and try to load my world the game crashes. After some testing I found out something really interesting: when I delete one mod I'm able to add another and the game doesn't crash while loading my world.

Game Version: Early Access CL#125236
SML: v2.2.1

**Crash Report:**
---
Version: 125236, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Assertion failed: O->GetClass()->ImplementsInterface(UFGSaveInterface::StaticClass()) [File:D:\ws\SB-200518130817-657\UE4\Games\FactoryGame\Intermediate\Build\Win64\FactoryGame\Inc\FactoryGame\FGSaveInterface.gen.cpp] [Line: 446]

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!IFGSaveInterface::Execute_PreLoadGame() [d:\ws\sb-200518130817-657\ue4\games\factorygame\intermediate\build\win64\factorygame\inc\factorygame\fgsaveinterface.gen.cpp:446]
FactoryGame_Win64_Shipping!FArchiveObjectTOCProxy::operator<<() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgsavesession.cpp:1280]
FactoryGame_Win64_Shipping!operator<<() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\containers\array.h:1100]
FactoryGame_Win64_Shipping!UFGSaveSession::SerializeLoadedObjects() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgsavesession.cpp:1482]
FactoryGame_Win64_Shipping!UFGSaveSession::LoadCompressedFileFromDisk() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgsavesession.cpp:778]
FactoryGame_Win64_Shipping!UFGSaveSession::LoadGame() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgsavesession.cpp:920]
FactoryGame_Win64_Shipping!AFGGameMode::InitGameState() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fggamemode.cpp:274]
FactoryGame_Win64_Shipping!AGameModeBase::PreInitializeComponents() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\gamemodebase.cpp:125]
FactoryGame_Win64_Shipping!ULevel::RouteActorInitialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\level.cpp:1823]
FactoryGame_Win64_Shipping!UWorld::InitializeActorsForPlay() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\world.cpp:3925]
FactoryGame_Win64_Shipping!UEngine::LoadMap() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12518]
FactoryGame_Win64_Shipping!UEngine::Browse() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\unrealengine.cpp:11777]
FactoryGame_Win64_Shipping!UEngine::TickWorldTravel() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\unrealengine.cpp:11975]
FactoryGame_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\gameengine.cpp:1355]
FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:9]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4028]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launch.cpp:168]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by G0mp3r** [comment]
I have the same problem with the same behaviour

**Comment by Archengius** [comment]
Uniform Nodes is broken and has corrupted your save. Remove it and fix your save in save editor by removing all InitMod_XX entries (XX being a number).
This issue has nothing to do with SML.
