### ISSUE TITLE
Generated `incomplete-data.json` schema out-of-date with ficsit.app expectation.

### ISSUE THREAD

**Issue by yesod-github** [satisfactorymodding/SatisfactoryModLoader#58]
Thanks for the continued work all!

The generated `incomplete-data.json` produced with information entered via Alpakit uses a schema that is no longer compatible with ficsit.app .json schema verification; subsequently, this will prohibit the mod to upload.

**Comment by mircearoata** [comment]
It has been updated 5 days ago, and the file name is no longer `incomplete-data.json`, but rather `data.json` as it contains all the information now. Please download the latest version of the project
