### ISSUE TITLE
IF SML and a random Mod is loaded, and the game exitet, the Satisfactory client crashs and stays up running as ghost process.

### ISSUE THREAD

**Issue by wofnull** [satisfactorymodding/SatisfactoryModLoader#63]
Hi there, 

i really don't know why https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/54 was closed beforehand. However i came across the exact same issue and were able to find at least the root cause, why the SML thinks Satisfactory is still running.

But lets start from Scratch:
- R9 3900x
- Nvidia 1080ti
- 32 GB RAM
- Install of SF is on NVME SSD / normal SSD

- Windows 10 Pro
- Satisfactory: Early Access
- SML 2.2.1
- Current Version of X3-Signs / Minmap / ExoSuit Mod / PermaDay / Area Actions ( all together or single loaded ).

When the client is shut down ( there is not even the need to load the savegame! ) , the game does not exit, it crashes, coming up with the UE4 Error Handler. 
This itself is annoying, but not as bad as the following up:

SML: States that Satisfactory is still running. 
- Checked in Taskmanager: Nope no Executable from Satisfactory Present
- Checked in Details in Taskmanager: Aswell no Executable visible
- Checked in Ressource Monitor Tool from Task Manager: an open running Satisfactory Executable is found, which does not attach to any local file and is in the state stopped, it has currently 0 Theads and a CPU Load of 0 aswell. It takes around 76 KB of RAM , so not much at all. However the task cannot be stopped / killed, on first try no response, and from second time on, an Access denied error comes up.
- Checked in ProcessMonitor from Sysinternals and found the same behaviour. Changing the Access rights of the running task itself did not help at all, still access denied.

After deeper search, i got  to the point, where nowhere a solution was found, and i reinstalled Satisfactory ( to another SSD aswell ) and found exact the same issue: Client starts and Stops normaly until SML and a random MOD is loaded, then the problems arise again.

The only way to get rid of the running process is to restart the whole pc, this leads to another problem that changing up the mods will NEED the PC to be restarted , as the SML denies changes to the Mods loaded until the process is ended.

Far worse is that EVERY Manual start of Satisfactory WORKS from Epic ( and Steam though ) and loads the last loaded mods aswell, but leads into the same Crash Problem at the end and leaves every time an additional Satisfactory Ghost Process running.

As this is only coming up with SML / Random Mods, i think the problem needs to be solved here.

**Comment by nicolewells** [comment]
Hi,

I am experiencing the same exact thing as the above post.

- Microsoft Windows 10 Pro Insider Preview (10.0.20221 Build 20221)
- Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2201 Mhz, 6 Core(s), 12 Logical Processor(s)
- NVIDIA GeForce GTX 1070 with Max-Q Design
- 32.0 GB RAM
- Satisfactory: Early Access
- SML 2.2.1
- Mods: Pak Utility and PermaDay

**Comment by chrisreid923** [comment]
I am having the same issue as above.

Microsoft Windows 10 Pro Insider Preview (10.0.20221 Build 20221)
AMD 3800X
NVIDIA GeForce RTX 2060 6GB
16.0 GB RAM
Satisfactory: Early Access
SML 2.2.1

**Comment by MOOOOs** [comment]
I have same issue here also.
Microsoft Windows 10 Pro 2004 19041.572
Intel I5-7400 
NVIDIA GeForce GTX 1050TI
8 GB RAM
Satisfactory: Early Access
SML 2.2.1

**Comment by omegaprime02** [comment]
I've seen this as well both with when running Early Access SML and when running the newest, unmodified, Experimental build, from what I've seen the Satisfactory process tucks inside the expanded list of Steam processes in Task Manager.  Might be wise to double check that zone as well.

The information applicable to SML is as follows:
Windows 10 Home 10.0.18363
Intel i7-8700
NVIDIA GeForce GTX 1080
16 GB RAM
Satisfactory: Early Access
SML 2.3.1

**Comment by budak7273** [comment]
Closing this since it was likely resolved by SML3 and there have been no more reports of it since.
