### ISSUE TITLE
Satisfactory Mod error

### ISSUE THREAD

**Issue by Lukas1612Ls** [satisfactorymodding/SatisfactoryModLoader#64]
Wenn ich Satisfactory Mod Öffne dann habe ich eine Fehler Meldung, Da steht dann da:
"Error loading with other Mod"
Was kann ich machen?

**Comment by budak7273** [comment]
Closing this issue since it lacks details relating to the issue, even when translated, and is almost a year old. If it was an SML-related issue, it was likely fixed by the release of SML3.
