### ISSUE TITLE
Builder scrollbar

### ISSUE THREAD

**Issue by dragonofmercy** [satisfactorymodding/SatisfactoryModLoader#67]
Hi,
I have an issue everytime I use SML, when you open the builder the scrollbar is displayed like below.

![odzfqyu9uoq51](https://user-images.githubusercontent.com/140013/101331817-c8bb1e00-3874-11eb-9fa2-e3ed1f7e641f.png)

I have also tested to only use loader without mods, same problem, I think it's not a mod problem.

**Comment by Ryder17z** [comment]
It's a GUI problem with the game.

**Comment by dragonofmercy** [comment]
Look at the first reply of this post https://www.reddit.com/r/SatisfactoryGame/comments/j3v027/scroll_bar_in_builder/
.I have checked on the code and find this:
https://github.com/satisfactorymodding/SatisfactoryModLoader/blob/master/Source/SML/player/BuildMenuTweaks.cpp
````csharp
//Create scroll box, populate it and set content
UScrollBox* ScrollBox = NewObject<UScrollBox>(RootWidget);
ScrollBox->SetScrollbarThickness(FVector2D(2.0f, 2.0f));
RootWidget->SetContent(ScrollBox);
ScrollBox->AddChild(ContentWidget);
````

**Comment by Nogg-aholic** [comment]
Issue is fixable but low priority for us. Either the GameDevs will take care of it ( Devs know about it ) or someone of us needs to take some Time to confirm a working solution.

**Comment by budak7273** [comment]
Closing this issue since it was resolved by base game a while back.
