### ISSUE TITLE
sml-shipping-dev-win64.zip cant be extracted

### ISSUE THREAD

**Issue by TheUnproductive** [satisfactorymodding/SatisfactoryModLoader#69]
Like the title says, I have not been able to extract the zip file from the newest release (2.2.1)

**Comment by Vilsol** [comment]
Could you post the error you are getting? What software are you using to extract it?

**Comment by TheUnproductive** [comment]
Windows gives me the Error Code 0x80004005, I am using the included zip extractor from windows

**Comment by TheUnproductive** [comment]
I have just tried it with 7-zip and it worked, so the problem seems to be with the included extractor in windows only

**Comment by budak7273** [comment]
Closing this issue since the problem has been resolved.
