### ISSUE TITLE
Unreal Engine Update 4.25

### ISSUE THREAD

**Issue by thlillyr** [satisfactorymodding/SatisfactoryModLoader#70]
The new experimental update changed the game to the Unreal engine V4.25 If you have the mod manager installed the game fails to launch. Deleting the loaders folder Specifically the UE4-SML-win64-shipping.dll allows the game to load correctly. All be it without mods loading.

**Comment by mircearoata** [comment]
There is an easier way than deleting the loaders folder: in SMM there are profiles, one of which is vanilla, so you can toggle the Experimental install to the vanilla profile and keep Early Access on the profile you used before.

**Comment by blazejkarwowski** [comment]
Is there any plans to adjust the code to support newest experimental? Unfortunately i'm not Unreal engine developer so only help i could offer is to test some cases.

**Comment by Ryder17z** [comment]
> Is there any plans to adjust the code to support newest experimental? Unfortunately i'm not Unreal engine developer so only help i could offer is to test some cases.

Have patience. It's being worked on...

**Comment by lilbigmouth** [comment]
@Ryder17z Who's working on it? More importantly, how can people help? It doesn't seem clear to me from this repository

**Comment by budak7273** [comment]
@lilbigmouth [Join the Discord](https://github.com/satisfactorymodding/SatisfactoryModLoader#discord-server) if you would like to help with development. The `sml-dev` branch has the most recent work.

**Comment by budak7273** [comment]
Closing this issue since SML3 released in April.
