### ISSUE TITLE
game not loading

### ISSUE THREAD

**Issue by flyingdutchie666** [satisfactorymodding/SatisfactoryModLoader#71]
hey there so the last few days SML loads up great and all the mods i like are there but then when i go to start the game it does not start the game, i tried in modded, and developer and both dont load but then when i go to vanilla it loads up fine.... i tired deleting all my mods and still nothing, tried loading each mod seperatly and nope nothing still. only works on vanilla, the modded and developer do not even work with no mods installed, am i missing something... it was fine last week>>>?

**Comment by Panakotta00** [comment]
If you are playing with experimental, then that's the problem...
because there was the Engine update and that causes mods to not work for a while on this version...
you either not play with the engine update and instead play on Early Access, or you wait till the next SML version releases
