### ISSUE TITLE
Satisfactory mod manager wont open

### ISSUE THREAD

**Issue by JustJackaBoi** [satisfactorymodding/SatisfactoryModLoader#73]
im quiet of new to mods and just clicked the first mods tutorial i saw installed the mod manager right away it wont open when i click it it opened in the tastmanager but thats it and i dont really know what to search for any solutions?

**Comment by samip5** [comment]
"Short version: Mods don't work yet on Experimental (Update 4). Use Early Access (Update 3).

CSS has updated the Experimental branch with the new engine, and now with Update 4 content. This means mods will not work until we can update and fix SMM/SML and modders update their mods. We hope to have everything up and working as soon as possible."

**Comment by JustJackaBoi** [comment]
The thing is i cant even open the manager i click it and nothing happens

**Comment by lilbigmouth** [comment]
@JustJackaBoi IN C:\Users\<Your username>\AppData\Local\Programs\Satisfactory Mod Manager there should be a file called logging.log . Does it contain anything after you attempt to open mod manager?

**Comment by budak7273** [comment]
Closing this since it was likely solved by the release of SML3 in April. If this issue persists, please re-open it on the [SMM github](https://github.com/satisfactorymodding/SatisfactoryModManager) instead, since that is what it relates to.
