### ISSUE TITLE
Black screen after adding profiles

### ISSUE THREAD

**Issue by yous00** [satisfactorymodding/SatisfactoryModLoader#79]
After creating a new profile the screen turns black. buttons can still be clicked, even though u cant see them. (restarting fixes this tho!)

**Comment by yous00** [comment]
Thanks for updating it btw!! <3

**Comment by Panakotta00** [comment]
It sounds like you are talking about the Satisfactory Mod Manager, plz refer to [this ](https://github.com/satisfactorymodding/SatisfactoryModManager) repository.
