### ISSUE TITLE
Can't even launch the Game through the Mod Manager

### ISSUE THREAD

**Issue by HelpIamHavingProblem** [satisfactorymodding/SatisfactoryModLoader#80]
I'm pressing on "Launch Satisfactory" and nothing's happening

Here's a picture of my Mod Manager
https://user-images.githubusercontent.com/82467773/114595708-faaf1780-9c8e-11eb-8419-0220ba7167f2.png

**Comment by Orchiwi** [comment]
Same problem for me

**Comment by Norixbtw** [comment]
Same pls help

**Comment by HelpIamHavingProblem** [comment]
I can only guess it's with the new update

**Comment by HelpIamHavingProblem** [comment]
Nevermind, I just had to restart my pc
