### ISSUE TITLE
Modloader can launch Satisfactory but does not apply mods

### ISSUE THREAD

**Issue by ThatSaltyDevil** [satisfactorymodding/SatisfactoryModLoader#83]
I tested it a couple times, but it seems that despite the issue with SML to open the game being fixed, I found another issue in that the mods which are compatible are not showing in any interface. This leads me to believe that the mods are not being applied at all. There are several mods which come with assets that just aren't showing up in the build menu, nor as being unlockable in the Hub. (i.e. Structural Solutions, Ficsit Cam, etc.)

UPDATE: After some tinkering I discovered using any profile that was used prior, the version display in "install" is stuck with the older version of the loader. Using another profile, in this case the development profile, allowed this to change to version 3.0.0. So... this may not be a bug per se.

**Comment by Ryder17z** [comment]
This is from the related Discord server:

```
SML3 and the Update 4 modding tools have been released!
This includes the Mod Manager (SMM), ficsit.app (SMR), the mod loader (SML) and the modding documentation!

This release is compatible with Update 4, which is currently on Experimental, and will be merged into to Early Access tomorrow. But!

!!! That doesn't mean that you will be able to play modded in Update 4 right away. :octagonal_sign:

:warning: The Mod Manager incorrectly reports U3 mods as compatible with U4.
This will be fixed very soon. Read below for more details.

!!! The Mod Manager is experiencing some problems with Update 3 content.

Although we have given mod devs advance and access to the tools to update, most mods still need to be updated for the new game version. This will take time, and some mods will sadly not make the transition, as their creators may have moved on. That being said, we are sure that the community will do their best to bring the maximum of mods back to a working state.

How do I know when a mod is ready for Update 4?

Starting tomorrow, it'll be easy! When U4 is released to the Early Access branch, every Update 3/SML2 mod will be marked as outdated on ficsit.app and the Mod Manager. After that point, any mod that isn't marked as outdated should be compatible with Update 4.

Can I use my modded Update 3 saves in Update 4?

It depends on the mod, but the answer is most likely 'yes.' SML3 has a system in place to help with this transition, so assuming the mod dev has not made major changes to their mod, it should work. However, if a mod has not yet been updated, you will lose its content if you try to play before that mod is ready.
```

**Comment by Ryder17z** [comment]
That was 3 days ago so we are still waiting for SML to get updated, then all the mods.

**Comment by ThatSaltyDevil** [comment]
Thank you for the information. I am not a part of the discord and did not see documentation of the issue. My apologies for reiterating an issue that was already known. I did not suspect that mods would be working right away. Just trying to make sure someone was tracking.

**Comment by budak7273** [comment]
Closing this issue as it has been resolved.
